kxk = require "kxk/kxk"

test("kseg", function()
    test("pop", function()
        local s = kseg("../")
        s:pop()
        test.cmp(s:str(), "..")
        
        s = kseg("◂▸○●")
        s:pop()
        test.cmp(s:str(), "◂▸○")
        s:pop()
        test.cmp(s:str(), "◂▸")
    end)
    
    test("push", function()
        local s = kseg()
        test.cmp(#s, 0)
        s:push("●")
        test.cmp(s:str(), "●")
        test.cmp(#s, 1)
        s:push("▪")
        test.cmp(s:str(), "●▪")
        test.cmp(#s, 2)
        s:push(" ")
        test.cmp(s:str(), "●▪ ")
        test.cmp(#s, 3)
    end)
    
    test("rpad", function()
        local s = kseg("▴")
        s:rpad(2)
        test.cmp(s:str(), "▴ ")
        s:rpad(4)
        test.cmp(s:str(), "▴   ")
        s:rpad(2)
        test.cmp(s:str(), "▴   ")
    end)
    
    test("trim", function()
        local s = kseg(" ▴  ")
        s:trim()
        test.cmp(s:str(), "▴")
        
        s = kseg(" ▴  ")
        s:rtrim()
        test.cmp(s:str(), " ▴")
        
        s = kseg(" ▴  ")
        s:ltrim()
        test.cmp(s:str(), "▴  ")
        
        s = kseg("\n\n ▴  \n  \n")
        s:trim()
        test.cmp(s:str(), "▴")
    end)
    
    test("emojii", function()
        local s = kseg("🧑")
        test.cmp(#s, 1)
        
        s = kseg("🧑‍🌾")
        test.cmp(#s, 3)
        test.cmp(s[#s], "🌾")
        s:pop()
        s:pop()
        test.cmp(#s, 1)
        test.cmp(s:str(), "🧑")
    end)
    
    test("is", function()
        local a = kseg("")
        test.cmp(a:is(kseg), true)
        test.cmp(a:is(array), true)
        test.cmp(a:is(table), false)
        test.cmp(a:is(false), false)
        test.cmp(a:is(true), false)
        test.cmp(a:is(nil), false)
    end)
    end)