kxk = require "kxk/kxk"
strg = require "kxk/strg"

test("kseg", function()
    test("static", function()
        test.cmp(kseg.rep(4):str(), "    ")
        test.cmp(kseg.rep(4, 'x'):str(), "xxxx")
        test.cmp(kseg.rep(2, 'xy'):str(), "xyxy")
        
        test.cmp(kseg.segiAtWidth(kseg(''), 1), 0)
        test.cmp(kseg.segiAtWidth(kseg('a'), 1), 1)
        test.cmp(kseg.segiAtWidth(kseg('a'), 2), 1)
        test.cmp(kseg.segiAtWidth(kseg('abc'), 2), 2)
        test.cmp(kseg.segiAtWidth(kseg('ab3'), 3), 3)
        test.cmp(kseg.segiAtWidth(kseg('ab3'), 4), 3)
        
        test.cmp(kseg.segiAtWidth(kseg('🧑🧑'), 1), 1)
        test.cmp(kseg.segiAtWidth(kseg('🧑🧑'), 2), 1)
        test.cmp(kseg.segiAtWidth(kseg('🧑🧑'), 3), 2)
        test.cmp(kseg.segiAtWidth(kseg('🧑🧑'), 4), 2)
        test.cmp(kseg.segiAtWidth(kseg('🧑🧑'), 5), 2)
        test.cmp(kseg.segiAtWidth(kseg('🧑🧑'), 6), 2)
    end)
    
    test("construct", function()
        local s = kseg()
        test.cmp(s:str(), "")
        s = kseg("  ")
        test.cmp(s:str(), "  ")
        s = kseg(kseg("xx"))
        test.cmp(s:str(), "xx")
        s = kseg(kseg(kseg("yy")))
        test.cmp(s:str(), "yy")
        local st = strg("zz")
        s = kseg(strg("zz"))
        test.cmp(s:str(), "zz")
    end)
    
    test("find", function()
        local s = "a  b"
        test.cmp(s:find(" "), 2)
        test.cmp(s:find("  "), 2)
        test.cmp(s:find(" b"), 3)
        test.cmp(s:find("b"), 4)
    end)
    
    test("pop", function()
        local s = kseg("../")
        s:pop()
        test.cmp(s:str(), "..")
        
        s = kseg("◂▸○●")
        s:pop()
        test.cmp(s:str(), "◂▸○")
        s:pop()
        test.cmp(s:str(), "◂▸")
    end)
    
    test("push", function()
        local s = kseg()
        test.cmp(#s, 0)
        s:push("●")
        test.cmp(s:str(), "●")
        test.cmp(#s, 1)
        s:push("▪")
        test.cmp(s:str(), "●▪")
        test.cmp(#s, 2)
        s:push(" ")
        test.cmp(s:str(), "●▪ ")
        test.cmp(#s, 3)
    end)
    
    test("rpad", function()
        local s = kseg("▴")
        s:rpad(2)
        test.cmp(s:str(), "▴ ")
        s:rpad(4)
        test.cmp(s:str(), "▴   ")
        s:rpad(2)
        test.cmp(s:str(), "▴   ")
    end)
    
    test("trim", function()
        local s = kseg(" ▴  ")
        s:trim()
        test.cmp(s:str(), "▴")
        
        s = kseg(" ▴  ")
        s:rtrim()
        test.cmp(s:str(), " ▴")
        
        s = kseg(" ▴  ")
        s:ltrim()
        test.cmp(s:str(), "▴  ")
        
        s = kseg("\n\n ▴  \n  \n")
        s:trim()
        test.cmp(s:str(), "▴")
    end)
    
    test("slice", function()
        local s = kseg("abc")
        test.cmp(s:slice(1):str(), "abc")
        test.cmp(s:slice(2):str(), "bc")
        test.cmp(s:slice(3):str(), "c")
        test.cmp(s:slice(4, 3):str(), "")
        test.cmp(s:slice(4, 4):str(), "")
        test.cmp(s:slice(4):str(), "")
    end)
    
    test("emojii", function()
        local s = kseg("🧑")
        test.cmp(#s, 1)
        
        s = kseg("🧑‍🌾")
        test.cmp(#s, 3)
        test.cmp(s[#s], "🌾")
        s:pop()
        s:pop()
        test.cmp(#s, 1)
        test.cmp(s:str(), "🧑")
    end)
    
    test("segiAtWidth", function()
        test.cmp(kseg.segiAtWidth(kseg("abc"), 1), 1)
        test.cmp(kseg.segiAtWidth(kseg("abc"), 2), 2)
        test.cmp(kseg.segiAtWidth(kseg("abc"), 3), 3)
        
        test.cmp(kseg.segiAtWidth(kseg("▸◌◂"), 1), 1)
        test.cmp(kseg.segiAtWidth(kseg("▸◌◂"), 2), 2)
        test.cmp(kseg.segiAtWidth(kseg("▸◌◂"), 3), 3)
        
        test.cmp(kseg.segiAtWidth("abc", 1), 1)
        test.cmp(kseg.segiAtWidth("abc", 2), 2)
        test.cmp(kseg.segiAtWidth("abc", 3), 3)
        
        test.cmp(kseg.segiAtWidth("▸◌◂", 1), 1)
        test.cmp(kseg.segiAtWidth("▸◌◂", 2), 2)
        test.cmp(kseg.segiAtWidth("▸◌◂", 3), 3)
    end)
    
    test("eql", function()
        test.cmp((kseg("abc") == kseg("abc")), false)
        
        test.cmp(kseg("abc"):eql(kseg("abc")), true)
        
        test.cmp(kseg.eql("abc", "abc"), true)
        test.cmp(kseg.eql("abc", kseg("abc")), true)
        test.cmp(kseg.eql(kseg("abc"), "abc"), true)
    end)
    
    test("is", function()
        local a = kseg("")
        test.cmp(a:is(kseg), true)
        test.cmp(a:is(array), true)
        test.cmp(a:is(table), false)
        test.cmp(a:is(false), false)
        test.cmp(a:is(true), false)
        test.cmp(a:is(nil), false)
    end)
    
    test("count", function()
        local s = kseg("__hellooo")
        test.cmp((s[#s] == "o"), true)
        test.cmp((s:slice(#s):str() == "o"), true)
        test.cmp(kseg.tailCount(s, "o"), 3)
        test.cmp(kseg.tailCount("__hellooo", "o"), 3)
        
        test.cmp(kseg.headCount(s, "_"), 2)
        test.cmp(kseg.headCount("__hellooo", "_"), 2)
        
        test.cmp(kseg.tailCount("◂◂○○●", "●"), 1)
        test.cmp(kseg.headCount("◂◂○○●", "◂"), 2)
        
        test.cmp(kseg.tailCountWord(kseg("1  2 33")), 2)
        
        test.cmp(kseg.headCountWord(kseg("1  2 33")), 1)
        test.cmp(kseg.headCountWord(kseg("  2 33")), 0)
        test.cmp(kseg.headCountWord(kseg(".  2 33")), 0)
        test.cmp(kseg.headCountWord(kseg("x233")), 4)
        test.cmp(kseg.headCountWord(kseg("x233 ")), 4)
        
        test.cmp(kseg.tailCount(" ", ""), 0)
        test.cmp(kseg.tailCount(" ", " "), 1)
        test.cmp(kseg.tailCount("  ", " "), 2)
    end)
    
    test("spanForClosestWordAtColumn", function()
        test.cmp(kseg.spanForClosestWordAtColumn(kseg('abc def'), 1), array(1, 4))
        test.cmp(kseg.spanForClosestWordAtColumn(kseg('abc def'), 2), array(1, 4))
        test.cmp(kseg.spanForClosestWordAtColumn(kseg('abc def'), 3), array(1, 4))
        test.cmp(kseg.spanForClosestWordAtColumn(kseg('abc def'), 4), array(5, 8))
        test.cmp(kseg.spanForClosestWordAtColumn(kseg('ab  def'), 3), array(1, 3))
        test.cmp(kseg.spanForClosestWordAtColumn(kseg('ab  def'), 4), array(5, 8))
        
        test.cmp(kseg.spanForClosestWordAtColumn(kseg('     '), 0), array(0, 0))
        test.cmp(kseg.spanForClosestWordAtColumn(kseg('     '), 2), array(2, 2))
        test.cmp(kseg.spanForClosestWordAtColumn(kseg('     '), 3), array(3, 3))
        
        test.cmp(kseg.spanForClosestWordAtColumn(kseg('   xy'), 2), array(4, 6))
        test.cmp(kseg.spanForClosestWordAtColumn(kseg('xy   '), 3), array(1, 3))
        
        test.cmp(kseg.spanForClosestWordAtColumn("   aa123   ", 1), array(4, 9))
    end)
    end)