--[[
    000   0000000   0000000   000   000   0000000    
    000  000       000   000  0000  000  000         
    000  000       000   000  000 0 000  0000000     
    000  000       000   000  000  0000       000    
    000   0000000   0000000   000   000  0000000     
--]]

local icons = {
    dir = '', 
    dir_close = '', 
    dir_open = '', 
    gear = '', 
    robot = 'ﮧ', 
    apple = '', 
    linux = '', 
    windows = '', 
    -- 00000000  000  000      00000000  , 
    -- 000       000  000      000       , 
    -- 000000    000  000      0000000   , 
    -- 000       000  000      000       , 
    -- 000       000  0000000  00000000  , 
    file = '', 
    kode = '', 
    noon = '', 
    ai = '', 
    bash = '', 
    bat = '', 
    bmp = '', 
    c = '', 
    cc = '', 
    clj = '', 
    cljs = '', 
    coffee = '', 
    conf = '', 
    cpp = '', 
    cs = '', 
    css = '', 
    d = '', 
    dart = '', 
    db = '', 
    diff = '', 
    ejs = '', 
    elm = '', 
    erl = '', 
    ex = '', 
    fish = '', 
    fs = '', 
    gif = '', 
    go = '', 
    h = '', 
    haml = '', 
    hbs = '', 
    hpp = '', 
    hs = '', 
    htm = '', 
    html = '', 
    ico = '', 
    icns = '', 
    ini = '', 
    java = '', 
    jl = '', 
    jpeg = '', 
    jpg = '', 
    js = '', 
    json = '', 
    jsx = '', 
    less = '', 
    lua = '', 
    md = '', 
    mjs = '', 
    mk = '', 
    ml = 'λ', 
    mm = '', 
    nim = '', 
    kim = '', 
    kua = '☾', 
    nix = '', 
    php = '', 
    pl = '', 
    png = '', 
    pp = '', 
    plist = '', 
    pug = '', 
    py = '', 
    pyc = '', 
    r = 'ﳒ', 
    rake = '', 
    rb = '', 
    rproj = '鉶', 
    rs = '', 
    rss = '', 
    sass = '', 
    scala = '', 
    scss = '', 
    sh = '', 
    slim = '', 
    sln = '', 
    sol = 'ﲹ', 
    sql = '', 
    styl = '', 
    suo = '', 
    swift = '', 
    tex = 'ﭨ', 
    toml = '', 
    ts = '', 
    tsx = '', 
    vim = '', 
    vue = '﵂', 
    webp = '', 
    xul = '', 
    yaml = '', 
    yml = '', 
    zsh = ''
    }

return icons